  - name: Install prerequisites on RedHat
    dnf:
      name: dnf-plugins-core
      state: present
    when: ansible_os_family == "RedHat"
  - name: Add Docker CE repo on RedHat
    get_url:
      url: "{{ docker_repo_url_redhat }}"
      dest: /etc/yum.repos.d/docker-ce.repo
    when: ansible_os_family == "RedHat"
    notify: Restart Docker
  - name: Install Docker packages on RedHat
    dnf:
      name: "{{ docker_packages_redhat }}"
      state: present
    when: ansible_os_family == "RedHat"
    notify: Restart Docker
  - name: Install prerequisites on Debian
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
    when: ansible_os_family == "Debian"
  - name: Add Docker GPG key on Debian
    apt_key:
      url: "{{ docker_repo_key_url_debian }}"
      state: present
    when: ansible_os_family == "Debian" 
  - name: Add Docker repository on Debian
    apt_repository:
      repo: "deb [arch=amd64] {{ docker_repo_url_debian }} {{ ansible_lsb.codename }} stable"
      state: present
    when: ansible_os_family == "Debian"
    notify: Restart Docker
  - name: Install Docker packages on Debian
    apt:
      name: "{{ docker_packages_debian }}"
      state: present
    when: ansible_os_family == "Debian"
    notify: Restart Docker
  - name: Enable and start Docker service
    systemd:
      name: docker
      enabled: true
      state: started
